.\" Hey, EMACS: -*- nroff -*-
.\" Copyright (C) 2015 Sergio Durigan Junior <sergiodj@sergiodj.net>
.\"
.\" This document is free software.  You may distribute and/or modify
.\" it under the terms of:
.\"
.\" * The GNU General Public License, as published by the Free
.\"   Software Foundation, version 3 or (at your option) any later
.\"   version.  You should have received a copy of the GNU General
.\"   Public License along with this program.  If not, see
.\"   <http://www.gnu.org/licenses/>.
.\"
.\" $Id$
.TH OSCAR 1 "version 1.0.2" "May 2020"
.\" Please adjust this date whenever revising the manpage.
.\"

.SH NAME

OSCAR \- OpenSource CPAP Analysis Reporter.

.SH DESCRIPTION

\fBOSCAR\fP is a derivative of SleepyHead version 1.1.0,created when
that was abandoned by Mark Watkins.

\fBSleepyHead\fP was a cross platform, opensource sleep tracking program
for reviewing CPAP and Oximetry data, which are devices used in the
treatment of Sleep Disorders like Obstructive Sleep Apnea. It was released
under the GPL version 3 license. See the file COPYING for those details.

SleepyHead was written by Mark Watkins (aka Jedimark), an Australian
software developer afflicted with sleep apnea.

SleepyHead was copyright (C) 2011-2018 by Mark Watkins <mark@jedimark.net>

Portions of OSCAR are copyright (c) 2019, 2020 by The OSCAR Team
<oscar@oscar-team.org>

.SH OPTIONS

This program does not accept command-line options.

.SH BUGS

\fB<https://gitlab.com/pholy/OSCAR-code>\fP.

.SH HOMEPAGE

\fB<https://sleepfiles.com/OSCAR/>\fP

.SH AUTHORS

Mark Watkins <mark@jedimark.net>
The OSCAR Team <oscar@oscar-team.org>


.PP

This manual page was written by Johan Heikkilä  <johan.heikkila@gmail.com>.
